# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: macos-latest

steps:
- script: yarn install
  displayName: Install Dependencies

- script: |
    cd android
    ./gradlew app:assembleRelease
  displayName: Generate apk
