trigger:
- main

pool:
  vmImage: macos-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.18.x'

- script: yarn install
  displayName: Install Dependencies

- script: |
    cd android
    EXPO_PUBLIC_WHITELABEL=$(EXPO_PUBLIC_WHITELABEL) && ./gradlew app:assembleRelease
  displayName: Generate apk

- task: PublishBuildArtifacts@1
  displayName: 'Publish APK to artifacts'
  inputs:
    PathtoPublish: 'android/app/build/outputs/apk/release'
    ArtifactName: 'android'
    publishLocation: Container