trigger:
- main

pool:
  vmImage: macos-latest

parameters:
  - name: whitelabels
    type: object
    default:
      - name: ucondo
      - name: mrv

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.18.x'

- script: yarn install
  displayName: Install Dependencies

- ${{ each whitelabel in parameters.whitelabels }}:
  - script: cd android && EXPO_PUBLIC_WHITELABEL=${{ whitelabel.name }} && ./gradlew app:assembleRelease
    displayName: 'Build ${{ whitelabel.name }} whitelabel'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish ${{ whitelabel.name }} whitelabel APK to artifacts'
    inputs:
      PathtoPublish: 'android/app/build/outputs/apk/release'
      ArtifactName: '${{ whitelabel.name }}'
      publishLocation: Container

