trigger:
- main

pool:
  vmImage: macos-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.18.x'

- script: yarn install
  displayName: Install Dependencies

- script: |
    cd android
    ./gradlew app:assembleRelease
  displayName: Generate apk
