trigger:
- main

pool:
  vmImage: macos-latest

parameters:
  - name: whitelabels
    type: object
    default:
      - name: ucondo
      - name: mrv

stages: 
  - stage: 'prebuild'
    jobs: 
      - job: 'prebuild'
        steps:
        - task: NodeTool@0
          inputs:
            versionSource: 'spec'
            versionSpec: '18.18.x'

        - script: yarn install
          displayName: Install Dependencies

  - stage: 'build'
    dependsOn: 'prebuild'
    jobs:
      - ${{ each whitelabel in parameters.whitelabels }}:
        - job: 'run_for_each_whitelabel_${{ whitelabel.name }}'
          displayName: 'Using ${{ whitelabel.name }} whitelabel'
          steps:
            - script: cd android && EXPO_PUBLIC_WHITELABEL=${{ whitelabel.name }} && ./gradlew app:assembleRelease

  - stage: 'publish'
    dependsOn: 'build'
    jobs:
    - job: 'publish'
      steps:
      - task: PublishBuildArtifacts@1
        displayName: 'Publish APK to artifacts'
        inputs:
          PathtoPublish: 'android/app/build/outputs/apk/release'
          ArtifactName: 'android'
          publishLocation: Container