workflows:
  sample-workflow:
    name: android ucondo
    instance_type: mac_mini_m2
    environment: 
      vars: 
        EXPO_PUBLIC_WHITELABEL: ucondo
        node: 18.18.x
    scripts:
        - name: Install dpendencies
          script: |
            npm install
        - name: Build 
          script: |
            cd android && EXPO_PUBLIC_WHITELABEL=$EXPO_PUBLIC_WHITELABEL && ./gradlew app:assembleRelease
    artifacts: 
       - android/app/build/outputs/apk/release/*.apk
